[2024-01-27T02:38:01.301+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_forecast_pipeline.extract_and_transform manual__2024-01-27T02:37:14.650410+00:00 [queued]>
[2024-01-27T02:38:01.319+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_forecast_pipeline.extract_and_transform manual__2024-01-27T02:37:14.650410+00:00 [queued]>
[2024-01-27T02:38:01.320+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-27T02:38:01.361+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_and_transform> on 2024-01-27 02:37:14.650410+00:00
[2024-01-27T02:38:01.412+0000] {standard_task_runner.py:60} INFO - Started process 12979 to run task
[2024-01-27T02:38:01.600+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_forecast_pipeline', 'extract_and_transform', 'manual__2024-01-27T02:37:14.650410+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sales_forecast_pipeline.py', '--cfg-path', '/tmp/tmpbjpbhw3x']
[2024-01-27T02:38:01.602+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask extract_and_transform
[2024-01-27T02:38:02.358+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_forecast_pipeline.extract_and_transform manual__2024-01-27T02:37:14.650410+00:00 [running]> on host 7ae7c919d654
[2024-01-27T02:38:17.674+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_forecast_pipeline' AIRFLOW_CTX_TASK_ID='extract_and_transform' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T02:37:14.650410+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-27T02:37:14.650410+00:00'
[2024-01-27T02:38:18.000+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 38, in extract_and_transform
    in_files = [extract(os.path.join(raw_dir, x)) for x in raw_files]
  File "/opt/airflow/dags/etl.py", line 38, in <listcomp>
    in_files = [extract(os.path.join(raw_dir, x)) for x in raw_files]
  File "/opt/airflow/dags/etl.py", line 6, in extract
    df = pd.read_excel(path, nrows=11)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-01-27T02:38:18.333+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=sales_forecast_pipeline, task_id=extract_and_transform, execution_date=20240127T023714, start_date=20240127T023801, end_date=20240127T023818
[2024-01-27T02:38:18.666+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task extract_and_transform (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 12979)
[2024-01-27T02:38:18.783+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-27T02:38:19.083+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
